trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns
#View for selecting pickup day
#View for requesting extra pickup
#View to suspend account
#

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('details/', views.details, name='details'),
    path('change_pickup/', views.change_pickup, name='change_pickup'),
    path('extra_pickup/', views.extra_pickup, name='extra_pickup'),
    path('suspend_service/', views.suspend_service, name='suspend_service'),

    #Pickup day
    #Suspending service
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('my_accounts/', views.my_accounts, name='my_accounts'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),

]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<nav class="navbar navbar-light bg-light">
  <div class="container-flex">
      <a class="navbar-brand">Hot Tra$h</a>
      {% if user.is_authenticated %}
      {% for group in user.groups.all%}
      {% if group.name == "Customers" %}

        <a class="btn btn-outline-success" href="{% url 'customers:index' %}">Home</a>
        <a class="btn btn-outline-success" href="{% url 'customers:details' %}">My Account</a>
        <a class="btn btn-outline-success" href="{% url 'customers:change_pickup' %}">Change Pickup Day</a>
        <a class="btn btn-outline-success" href="{% url 'customers:extra_pickup' %}">Schedule Extra Pickup</a>
        <a class="btn btn-outline-success" href="{% url 'customers:suspend_service' %}">Suspend Your Service</a>

    {% elif group.name == "Employees" %}

    <a class="btn btn-outline-success" href="{% url 'employees:index' %}">Home</a>
    <a class="btn btn-outline-success" href="{% url 'employees:my_accounts' %}">My Accounts</a>

    {% endif %}
  {% endfor %}
  <a class="btn btn-sm btn-outline-danger" href="{% url 'logout' %}">Log Out</a>
{% endif %}
  </div>
</nav>
<body>
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %} Home Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}