trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('my_accounts/', views.my_accounts, name='my_accounts'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),

]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    zip_code = models.IntegerField()

    def __str__(self):
        return self.first_name + " " + self.last_name

trash_collector/employees/views.py
from .models import Employee
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.apps import apps
from datetime import date
import calendar

# Create your views here.

#Displays pickupsf for:
    #Customers in employee zip code, where pickup day is today & service is not suspended OR there is a 1-time pickup scheduled for today
def index(request):
    user = request.user

    try:
        # This line inside the 'try' will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=user)
    except:
        return HttpResponseRedirect(reverse('employees:create'))

    Customer = apps.get_model('customers.Customer')
    all_customers = Customer.objects.all()
    matching_customers = []
    today = date.today()
    today_string = calendar.day_name[today.weekday()]
    for customer in all_customers:
        is_suspended = customer.suspension_start < today and customer.suspension_end > today
        if customer.has_extra_pickup and customer.extra_pickup_day == today:
            matching_customers.append(customer)
        elif customer.pickup_day == today_string and not is_suspended:
            matching_customers.append(customer)
    context = {
        'matching_customers': matching_customers
    }
    print(user)
    return render(request, 'employees/index.html', context)

#Display all ccustomers in zip code, option to filter by pickup day
def my_accounts(request):
    user = request.user
    logged_in_employee = Employee.objects.get(user=user)
    Customer = apps.get_model('customers.Customer')
    matching_customers = []
    
    if(request.method == "POST" and request.POST.get("pickup_day") != "All"):
        pickup_day = request.POST.get("pickup_day")
        all_customers = Customer.objects.filter(pickup_day=pickup_day)
    else:
        all_customers = Customer.objects.all()

    for customer in all_customers:
        if customer.zip_code == logged_in_employee.zip_code:
            matching_customers.append(customer)
    
    context = {
        'matching_customers': matching_customers
    }

    return render(request, 'employees/my_accounts.html', context)

def create(request):
    if request.method == "POST":
        user = request.user
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        zip_code = request.POST.get('zip_code')
        new_customer = Employee(user=user, first_name=first_name, last_name=last_name, zip_code=zip_code)
        new_customer.save()
        return render(request, 'employees/index.html')
    else:
         return render(request, 'employees/create.html')

def confirm_pickup(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(id=customer_id)


    if request.method == "POST":
        customer.current_balance -= 20
        customer.save()
        
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'customer': customer
        } 
        return render(request, 'employees/confirm_pickup.html', context)

#TODO - will select current customer, ask to confirm pickup, then on click will charge customer

trash_collector/employees/templates/employees/confirm_pickup.html
{% extends "base.html" %}

{% block title %}Confirm Customer Pickup{% endblock %}

{% block content %}
<h4>Confirm Pickup for:</h4>
<h4>{{ customer.first_name }} {{ customer.last_name }}</h4>
<form action ="{% url 'employees:confirm_pickup' customer.id %}", method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Pickup">
</form>
    
{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends "base.html" %}

{% block title %}Employee Account Creation{% endblock %}

{% block content %}

    <form action ="{% url 'employees:create' %}", method="POST">
        {% csrf_token %}
        First Name: <input type="text", name="first_name", id="first_name"><br />
        Last Name: <input type="text", name="last_name", id="last_name"><br />
        Zip Code: <input type="text", name="zip_code", id="zip_code"><br />
        <input type="submit" value="Create Account!">
    </form>
    
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Howdy, {{ user.username }}!

  <h4>Today's Pickups</h4>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Zip Code</th>
      <th>Current Balance</th>
      <th>Confirm Pickup</th>
    </tr>
    {% for customer in matching_customers %}
    <tr>
      <td>{{customer.first_name}}</td>
      <td>{{customer.last_name}}</td>
      <td>{{customer.zip_code}}</td>
      <td>{{customer.current_balance}}</td>
      <td><a class="btn btn-sm btn-outline-success" href="{% url 'employees:confirm_pickup' customer.id %}">Confirm Pickup</a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/my_accounts.html
{% extends 'base.html' %}

{% block title %}{% block header %} My Accounts: {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}

  <form action ="{% url 'employees:my_accounts' %}", method="POST">
    {% csrf_token %}
    <label for="pickup_day">Filter by Pickup Day:</label>
    <select name="pickup_day" id="pickup_day">
        <option value="All" selected>All</option>
        <option value="Monday">Monday</option>
        <option value="Tuesday">Tuesday</option>
        <option value="Wednesday">Wednesday</option>
        <option value="Thursday">Thursday</option>
        <option value="Friday">Friday</option>
    </select>
    <input type="submit" value="Filter">
</form>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Zip Code</th>
      <th>Pickup Day</th>
    </tr>
    {% for customer in matching_customers %}
    <tr>
      <td>{{customer.first_name}}</td>
      <td>{{customer.last_name}}</td>
      <td>{{customer.zip_code}}</td>
      <td>{{customer.pickup_day}}</td>

    </tr>
    {% endfor %}
  </table>
    {% for customer in matching_customers %}

    {% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}